---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Elizabeth Son"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/final-project-1-elizabethson](https://github.com/stat301-1-2023-fall/final-project-1-elizabethson)

:::

## Data source

"GDP Over Hours Worked"^[https://github.com/TheEconomist/the-economist-gdp-per-hour-estimates/blob/main/output-data/gdp_over_hours_worked.csv] is the dataset behind an article titled "All work and no play"^[https://www.economist.com/graphic-detail/2023/10/04/productivity-has-grown-faster-in-western-europe-than-in-america] from The Economist. There is a single dataset as a CSV file. The aim of the article was to measure productivity based on metrics such as PPP (Purchasing Power Parity) and hours worked. Some key variables are year (ranging from 1980 to 2022), country, unemployment rate, hours (working) per employed (person), and functions of GDP (Gross Domestic Product). 

The next 5 datasets^[https://www.kaggle.com/datasets/unsdsn/world-happiness] come from "The World Happiness Report"^[https://worldhappiness.report] which details happiness level by country calculated from Gallup World Poll data, which utilized surveys based on the Cantril ladder^[https://worldhappiness.report/about/]. The Cantril ladder asks respondents to rate their "own current lives" on a scale of 0 to 10 to determine an average "Happiness Score" by country. In addition to Happiness Score, there are six more relevant variables such as "healthy life expectancy." Each dataset corresponds to a year from 2015 to 2019. 

To join these datasets together, I will use the country variables from each of the datasets to create one large, combined dataset. Since the Happiness Score datasets are divided by year, I will make a new variable named "Year" in each dataset to combine them with the corresponding observations from `gdp_hours_worked`.

## Why this data

As an economics major, the focus of many of my classes have been quantitative, such as GDP and unemployment. What hasn't been addressed enough, however, is whether maximized productivity in the form of economic growth or power can also impact citizens' well-being. The ideal nation shouldn't just be wealthy and powerful, but also have happy citizens who can then contribute to society in more positive ways. Some preliminary questions that I have are:

1. Is there a correlation between Happiness Score and productivity? How about with hours worked?

2. Is there a "Laffer Curve"-like^[https://www.heritage.org/taxes/report/the-laffer-curve-past-present-and-future] relationship between Happiness Score and hours worked? (I expect that minimal hours worked does not necessarily equate to maximum happiness.)

## Data quality & complexity check

```{r}
library(readr)
library(tidyverse)
gdp_hours_worked <- read_csv("data/gdp_over_hours_worked.csv")
happy_2015 <- read_csv("data/2015.csv")
happy_2016 <- read_csv("data/2016.csv")
happy_2017 <- read_csv("data/2017.csv")
happy_2018 <- read_csv("data/2018.csv")
happy_2019 <- read_csv("data/2019.csv")
```
`gdp_hours_worked` has 11560 observations and 27 variables. 3 variables are categorical and 24 are numerical. Some of the numerical variables have missing values. 

`happy 2015`, `happy_2016`, `happy_2017`, `happy_2018`, `happy_2019` have 158, 157, 155, 156, and 156 observations respectively. Each dataset also has 12, 13, 12, 9, and 9 variables respectively. `happy_2015` and `happy_2016` have two categorical variables, while `happy_2017`, `happy_2018`, and `happy_2019` have one categorical variable. The remaining variables are numerical. There are no missing values in any of the Happiness Report datasets. 

## Potential data issues

Merging the datasets into one will be challenging because each observation in `gdp_hours_worked` represents a different year, while the Happiness Report datasets will have year as a variable. 

`gdp_hours_worked` is also a messy dataset because many values are missing. I will also have to look into finding documentation for the variables, because it is unclear what some of the variables are measuring (such as "iso2c").

## Misc

My data exploration will not only include visualizations by country, but also over time. Since the Happiness Report datasets only contain 5 years of data, the data over time combining all of the datasets will be restricted to that time period. 